// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Main from "../src/Main.res.mjs";

function pad(content) {
  return "  ".concat(content.replaceAll("\n", "\n  "));
}

var source = [
    "- Foobar",
    "- Hello"
  ].join("\n");

var wanted = ["<ul><li>Foobar</li><li>Hello</li></ul>"].join("");

var actual = Main.documentToString(Main.parseDocument(source));

if (actual !== wanted) {
  console.log("Test \"unordered list\" failed!");
  console.log("Wanted:");
  console.log(pad(wanted));
  console.log("Actual:");
  console.log(pad(actual));
}

export {
  pad ,
}
/* source Not a pure module */
