// Generated by ReScript, PLEASE EDIT WITH CARE


function toHTMLString(t) {
  switch (t) {
    case "Oblique" :
        return "em";
    case "Boldface" :
        return "strong";
    case "Monospaced" :
        return "code";
    case "Highlighted" :
        return "mark";
    case "Underscored" :
        return "ins";
    case "Strikethrough" :
        return "del";
    
  }
}

var Tag = {
  toHTMLString: toHTMLString
};

export {
  Tag ,
}
/* No side effect */
