// Generated by ReScript, PLEASE EDIT WITH CARE


function toString(t) {
  switch (t) {
    case "Italic" :
        return "emph";
    case "Strong" :
        return "strong";
    case "Delete" :
        return "del";
    case "Highlight" :
        return "mark";
    case "Underline" :
        return "ins";
    case "Monospace" :
        return "code";
    
  }
}

var Tag = {
  toString: toString
};

export {
  Tag ,
}
/* No side effect */
