// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Main from "./Main.res.mjs";

function compile(source) {
  return Main.spansToString(Main.parseParagraph(source));
}

console.log("Hello, world!");

[
    "Foo**bar**",
    "Fo**//ba//r**"
  ].forEach(function (x) {
      console.log(compile(x));
    });

export {
  compile ,
}
/*  Not a pure module */
