// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Markright__Compile$Markright from "./Markright__Compile.res.mjs";

var Concept;

var Extension;

var compile = Markright__Compile$Markright.compile;

export {
  Concept ,
  Extension ,
  compile ,
}
/* Markright__Compile-Markright Not a pure module */
