// Generated by ReScript, PLEASE EDIT WITH CARE


function newBlock(f) {
  return function (content, fullDocument) {
    return {
            hd: f(content, fullDocument),
            tl: /* [] */0
          };
  };
}

function newSpan(f) {
  return function (content, fullDocument) {
    return {
            hd: {
              TAG: "Paragraph",
              _0: {
                hd: f(content, fullDocument),
                tl: /* [] */0
              }
            },
            tl: /* [] */0
          };
  };
}

function newRaw(f) {
  return function (content, fullDocument) {
    return {
            hd: {
              TAG: "Raw",
              _0: f(content, fullDocument)
            },
            tl: /* [] */0
          };
  };
}

export {
  newBlock ,
  newSpan ,
  newRaw ,
}
/* No side effect */
